[build]
  publish = "."
  command = "npm install"

[functions]
  node_bundler = "esbundle"
  directory = "netlify/functions"

[[redirects]]
  from = "/upload"
  to = "/.netlify/functions/upload"
  status = 200

[[redirects]]
  from = "/media/*"
  to = "/.netlify/functions/media/:splat"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
